<script>
    import SimplePage from "$lib/SimplePage.svelte"
</script>

<SimplePage previous="/" next="/resume" --background-image="linear-gradient(to right, red,orange,yellow,green,blue,indigo,violet)" >
    <h1>About Me</h1>
    <h2>Stuff</h2>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati inventore voluptatum amet, eos modi nisi aperiam suscipit temporibus rerum quae quia perferendis itaque exercitationem saepe repellendus ipsum atque, commodi rem accusantium doloribus aut cum delectus distinctio. Aperiam ipsam esse corrupti laboriosam ut praesentium omnis vitae explicabo ad labore illo quae, tempore, impedit veritatis necessitatibus soluta qui facilis eaque pariatur fugiat quo nemo quisquam. Hic soluta, quod, nesciunt a consequuntur doloremque quidem quasi quas iste libero eius eaque maiores, cupiditate deserunt tenetur reprehenderit natus obcaecati. Vero sit, necessitatibus ipsa repellendus nisi in dolorem, ea placeat, reiciendis totam molestias quod id voluptate?</p> 
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati inventore voluptatum amet, eos modi nisi aperiam suscipit temporibus rerum quae quia perferendis itaque exercitationem saepe repellendus ipsum atque, commodi rem accusantium doloribus aut cum delectus distinctio. Aperiam ipsam esse corrupti laboriosam ut praesentium omnis vitae explicabo ad labore illo quae, tempore, impedit veritatis necessitatibus soluta qui facilis eaque pariatur fugiat quo nemo quisquam. Hic soluta, quod, nesciunt a consequuntur doloremque quidem quasi quas iste libero eius eaque maiores, cupiditate deserunt tenetur reprehenderit natus obcaecati. Vero sit, necessitatibus ipsa repellendus nisi in dolorem, ea placeat, reiciendis totam molestias quod id voluptate?</p> 
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati inventore voluptatum amet, eos modi nisi aperiam suscipit temporibus rerum quae quia perferendis itaque exercitationem saepe repellendus ipsum atque, commodi rem accusantium doloribus aut cum delectus distinctio. Aperiam ipsam esse corrupti laboriosam ut praesentium omnis vitae explicabo ad labore illo quae, tempore, impedit veritatis necessitatibus soluta qui facilis eaque pariatur fugiat quo nemo quisquam. Hic soluta, quod, nesciunt a consequuntur doloremque quidem quasi quas iste libero eius eaque maiores, cupiditate deserunt tenetur reprehenderit natus obcaecati. Vero sit, necessitatibus ipsa repellendus nisi in dolorem, ea placeat, reiciendis totam molestias quod id voluptate?</p> 
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati inventore voluptatum amet, eos modi nisi aperiam suscipit temporibus rerum quae quia perferendis itaque exercitationem saepe repellendus ipsum atque, commodi rem accusantium doloribus aut cum delectus distinctio. Aperiam ipsam esse corrupti laboriosam ut praesentium omnis vitae explicabo ad labore illo quae, tempore, impedit veritatis necessitatibus soluta qui facilis eaque pariatur fugiat quo nemo quisquam. Hic soluta, quod, nesciunt a consequuntur doloremque quidem quasi quas iste libero eius eaque maiores, cupiditate deserunt tenetur reprehenderit natus obcaecati. Vero sit, necessitatibus ipsa repellendus nisi in dolorem, ea placeat, reiciendis totam molestias quod id voluptate?</p> 
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati inventore voluptatum amet, eos modi nisi aperiam suscipit temporibus rerum quae quia perferendis itaque exercitationem saepe repellendus ipsum atque, commodi rem accusantium doloribus aut cum delectus distinctio. Aperiam ipsam esse corrupti laboriosam ut praesentium omnis vitae explicabo ad labore illo quae, tempore, impedit veritatis necessitatibus soluta qui facilis eaque pariatur fugiat quo nemo quisquam. Hic soluta, quod, nesciunt a consequuntur doloremque quidem quasi quas iste libero eius eaque maiores, cupiditate deserunt tenetur reprehenderit natus obcaecati. Vero sit, necessitatibus ipsa repellendus nisi in dolorem, ea placeat, reiciendis totam molestias quod id voluptate?</p> 
</SimplePage>

<a class="nav-button next" href="/projects">
    Next
</a>